{
 "title": "Juice-Shop Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "release", "query": "juice-shop" }
  ]
 },
 "panels": [
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5.*\",ingress=\"$release\"}[5m])) / sum(rate(nginx_ingress_controller_requests{ingress=\"$release\"}[5m]))\r"
    }
   ]
  },
  {
   "title": "Requests Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(nginx_ingress_controller_requests{ingress=\"$release\"}[5m]), \"status_code\", \"${1}xx\", \"status\", \"(.)..\")) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Requests Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_ingress_upstream_latency_seconds_sum{ingress=\"$release\"}[5m])) / sum(rate(nginx_ingress_controller_ingress_upstream_latency_seconds_count{ingress=\"$release\"}[5m])) * 1000\r"
    }
   ]
  }
 ]
}