---
image:
  tag: 7.5.1
ingress:
  enabled: true
annotations:
  kubernetes.io/ingress.class: nginx
service:
  port: 3000
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards
  notifiers:
    enabled: true
  datasources:
    enabled: true
notifiers:
  notifiers.yaml:
    notifiers:
    - name: E-Mail
      type: email
      uid: email1
      org_id: 1
      is_default: true
      settings:
        addresses: no@email.com
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server:9090
      access: proxy
      isDefault: true
