---
replicaCount: 2
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAuditEngine RelevantOnly
      SecAuditLogType Serial
      SecAuditLog /dev/stdout
  enabled: true
  tls:
    - secretName: juice-shop-tls
Resources:
  limits:
    cpu: 1
    memory: 512M
